version: '3.4'

services:
  webapp:
    image: webapp:dev
    build:
      target: development
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages
    volumes:
      - ${HOST_APP_ROOT_PATH}:/app
      - ${HOST_VS_REMOTE_DEBUGGER_PATH}:/remote_debugger:ro
      - ${HOST_NUGET_PACKAGE_PATH}:/root/.nuget/packages:ro
      - ${HOST_NUGET_FALLBACK_FOLDER}:/root/.nuget/fallbackpackages:ro
      - type: volume
        source: node_modules
        target: /modules/node_modules
        volume:
            nocopy: false
      - node_modules:/app/ClientApp/node_modules
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.2/webapp.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

volumes:
    node_modules: