version: "3.4"
services:
  webapp:
    build:
      context: ../../../webapp
      dockerfile: ../docker/deployment/Dockerfile
      target: runtime # the stage to build
    #image: jericmason/webapp:prod
    image: jericmason/production:private
    expose:
      - "5001" # Expose ports without publishing them to host machine - they'll only be accessible to linked services
    restart: always
    ports:
      - "80:5001" # HOST:CONTAINER
